###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.
# Create new hashed password: docker run authelia/authelia:latest authelia hash-password <new_password>
# https://docs.authelia.com/configuration/authentication/file.html

# List of users
users:
  user:
    displayname: "User"
    password: "passwort"
    email: user@email.com
    groups:
      - admins
      - dev
